import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { execFileSync } from 'child_process';
import matter from 'gray-matter';
import { DEFAULT_CATEGORIES } from '@versatly/clawvault-core/types.js';
import { hasQmd, withQmdIndexArgs } from '@versatly/clawvault-core/lib/search.js';
import { loadTemplateDefinition, renderDocumentFromTemplate, } from '@versatly/clawvault-core/lib/primitive-templates.js';
const CONFIG_FILE = '.clawvault.json';
function resolveVaultTarget(vaultOverride) {
    if (vaultOverride) {
        const vaultPath = path.resolve(vaultOverride);
        return { vaultPath, source: '--vault flag', existed: fs.existsSync(vaultPath) };
    }
    const envPath = process.env.CLAWVAULT_PATH?.trim();
    const home = os.homedir();
    if (envPath) {
        const vaultPath = path.resolve(envPath);
        return { vaultPath, source: 'CLAWVAULT_PATH', existed: fs.existsSync(vaultPath) };
    }
    const candidates = [
        { vaultPath: path.join(home, '.openclaw', 'workspace', 'memory'), source: 'OpenClaw default' },
        { vaultPath: path.resolve(process.cwd(), 'memory'), source: './memory' },
        { vaultPath: path.join(home, 'memory'), source: '~/memory' }
    ];
    for (const candidate of candidates) {
        if (fs.existsSync(candidate.vaultPath)) {
            return { ...candidate, existed: true };
        }
    }
    const fallback = candidates[0];
    return { ...fallback, existed: false };
}
function ensureVaultStructure(vaultPath) {
    fs.mkdirSync(vaultPath, { recursive: true });
    for (const category of DEFAULT_CATEGORIES) {
        fs.mkdirSync(path.join(vaultPath, category), { recursive: true });
    }
    const configPath = path.join(vaultPath, CONFIG_FILE);
    if (fs.existsSync(configPath))
        return false;
    const now = new Date().toISOString();
    const name = path.basename(vaultPath);
    const meta = {
        name,
        version: '1.0.0',
        created: now,
        lastUpdated: now,
        categories: DEFAULT_CATEGORIES,
        documentCount: 0,
        qmdCollection: name,
        qmdRoot: vaultPath
    };
    fs.writeFileSync(configPath, JSON.stringify(meta, null, 2));
    return true;
}
function writeBases(vaultPath, force) {
    const basesFiles = {
        'all-tasks.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
formulas:
  age: (now() - file.ctime).days
  status_icon: if(status == "blocked", "🔴", if(status == "in-progress", "🔨", if(status == "open", "⚪", "✅")))
views:
  - type: table
    name: All Active Tasks
    groupBy:
      property: status
      direction: ASC
    order:
      - formula.status_icon
      - file.name
      - status
      - owner
      - project
      - priority
      - blocked_by
      - formula.age
  - type: cards
    name: Task Board
    groupBy:
      property: status
      direction: ASC
    order:
      - file.name
      - owner
      - project
      - priority`,
        'blocked.base': `filters:
  and:
    - file.inFolder("tasks")
    - status == "blocked"
formulas:
  days_blocked: (now() - file.ctime).days
views:
  - type: table
    name: Blocked Tasks
    order:
      - file.name
      - owner
      - project
      - blocked_by
      - formula.days_blocked
      - priority`,
        'by-project.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
formulas:
  status_icon: if(status == "blocked", "🔴", if(status == "in-progress", "🔨", "⚪"))
views:
  - type: table
    name: By Project
    groupBy:
      property: project
      direction: ASC
    order:
      - formula.status_icon
      - file.name
      - status
      - owner
      - priority
  - type: cards
    name: Project Cards
    groupBy:
      property: project
      direction: ASC
    order:
      - file.name
      - owner
      - status`,
        'by-owner.base': `filters:
  and:
    - file.inFolder("tasks")
    - status != "done"
views:
  - type: table
    name: By Owner
    groupBy:
      property: owner
      direction: ASC
    order:
      - file.name
      - status
      - project
      - priority`,
        'backlog.base': `filters:
  and:
    - file.inFolder("backlog")
views:
  - type: table
    name: Backlog
    order:
      - file.name
      - source
      - project
      - file.ctime`,
    };
    let written = 0;
    for (const [filename, content] of Object.entries(basesFiles)) {
        const filePath = path.join(vaultPath, filename);
        if (force || !fs.existsSync(filePath)) {
            fs.writeFileSync(filePath, content);
            written++;
        }
    }
    return written;
}
const NEURAL_GRAPH_CSS = `/* ClawVault Graph Colors — Neural Neural Style */
/* Auto-generated by \`clawvault setup --theme neural\` */

body.theme-dark .graph-view .graph-view-container { background-color: #0a0a0a; }

body.theme-dark .graph-view .node.tag-person circle { fill: #00b4d8 !important; }
body.theme-dark .graph-view .node.tag-project circle { fill: #2d6a4f !important; }
body.theme-dark .graph-view .node.tag-decision circle { fill: #e8590c !important; }
body.theme-dark .graph-view .node.tag-lesson circle { fill: #fcc419 !important; }
body.theme-dark .graph-view .node.tag-commitment circle { fill: #e03131 !important; }
body.theme-dark .graph-view .node.tag-task circle { fill: #22b8cf !important; }
body.theme-dark .graph-view .node.tag-observation circle { fill: #7950f2 !important; }
body.theme-dark .graph-view .node.tag-handoff circle { fill: #845ef7 !important; }
body.theme-dark .graph-view .node.tag-daily circle { fill: #495057 !important; }

body.theme-dark .graph-view .node.is-focused circle {
  fill: #e8a430 !important; stroke: #e8a430 !important;
  stroke-width: 3px; filter: drop-shadow(0 0 6px #e8a430);
}

body.theme-dark .graph-view .link { stroke: rgba(45, 200, 120, 0.15) !important; }
body.theme-dark .graph-view .link.is-focused { stroke: rgba(45, 200, 120, 0.6) !important; }
body.theme-dark .graph-view .node text { fill: #c1c2c5 !important; font-size: 0.8em; }
`;
const MINIMAL_GRAPH_CSS = `/* ClawVault Graph Colors — Minimal */
/* Auto-generated by \`clawvault setup --theme minimal\` */

body.theme-dark .graph-view .node.tag-person circle { fill: #4a90e8 !important; }
body.theme-dark .graph-view .node.tag-project circle { fill: #4ae85d !important; }
body.theme-dark .graph-view .node.tag-decision circle { fill: #e85d4a !important; }
body.theme-dark .graph-view .node.tag-lesson circle { fill: #9b59b6 !important; }
body.theme-dark .graph-view .node.tag-task circle { fill: #e8a430 !important; }
`;
const NEURAL_COLOR_GROUPS = [
    { query: 'path:people', color: { a: 1, rgb: 47316 } },
    { query: 'path:projects', color: { a: 1, rgb: 2976335 } },
    { query: 'path:decisions', color: { a: 1, rgb: 15227916 } },
    { query: 'path:lessons', color: { a: 1, rgb: 16565273 } },
    { query: 'path:tasks', color: { a: 1, rgb: 2275535 } },
    { query: 'path:commitments', color: { a: 1, rgb: 14680369 } },
    { query: 'path:backlog', color: { a: 1, rgb: 9806262 } },
    { query: 'path:inbox', color: { a: 1, rgb: 15964178 } },
    { query: 'path:handoffs', color: { a: 1, rgb: 8675063 } },
    { query: 'path:ledger', color: { a: 1, rgb: 7950066 } },
];
const MINIMAL_COLOR_GROUPS = [
    { query: 'path:people', color: { a: 1, rgb: 4886760 } },
    { query: 'path:projects', color: { a: 1, rgb: 4909149 } },
    { query: 'path:decisions', color: { a: 1, rgb: 15228234 } },
    { query: 'path:lessons', color: { a: 1, rgb: 10181046 } },
    { query: 'path:tasks', color: { a: 1, rgb: 15246384 } },
];
function writeGraphColors(vaultPath, theme, force) {
    const obsidianDir = path.join(vaultPath, '.obsidian');
    if (!fs.existsSync(obsidianDir)) {
        // Not an Obsidian vault — skip silently
        return false;
    }
    const snippetsDir = path.join(obsidianDir, 'snippets');
    fs.mkdirSync(snippetsDir, { recursive: true });
    const snippetName = 'clawvault-graph';
    const snippetPath = path.join(snippetsDir, `${snippetName}.css`);
    if (!force && fs.existsSync(snippetPath)) {
        return false;
    }
    // Write CSS snippet
    const css = theme === 'neural' ? NEURAL_GRAPH_CSS : MINIMAL_GRAPH_CSS;
    fs.writeFileSync(snippetPath, css);
    // Enable snippet in appearance.json
    const appearancePath = path.join(obsidianDir, 'appearance.json');
    let appearance = {};
    if (fs.existsSync(appearancePath)) {
        try {
            appearance = JSON.parse(fs.readFileSync(appearancePath, 'utf-8'));
        }
        catch { /* ignore */ }
    }
    const snippets = appearance.enabledCssSnippets || [];
    if (!snippets.includes(snippetName)) {
        snippets.push(snippetName);
        appearance.enabledCssSnippets = snippets;
        fs.writeFileSync(appearancePath, JSON.stringify(appearance, null, 2));
    }
    // Configure graph.json colorGroups
    const graphPath = path.join(obsidianDir, 'graph.json');
    let graphConfig = {};
    if (fs.existsSync(graphPath)) {
        try {
            graphConfig = JSON.parse(fs.readFileSync(graphPath, 'utf-8'));
        }
        catch { /* ignore */ }
    }
    graphConfig.colorGroups = theme === 'neural' ? NEURAL_COLOR_GROUPS : MINIMAL_COLOR_GROUPS;
    if (theme === 'neural') {
        graphConfig.showTags = false;
        graphConfig.showAttachments = false;
        graphConfig.nodeSizeMultiplier = 1.2;
        graphConfig.lineSizeMultiplier = 0.8;
        graphConfig.textFadeMultiplier = 0;
        graphConfig.repelStrength = 10;
        graphConfig.linkDistance = 250;
        graphConfig.centerStrength = 0.5;
    }
    fs.writeFileSync(graphPath, JSON.stringify(graphConfig, null, 2));
    return true;
}
function getQmdConfig(vaultPath) {
    const configPath = path.join(vaultPath, CONFIG_FILE);
    if (fs.existsSync(configPath)) {
        try {
            const meta = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
            return {
                collection: meta.qmdCollection || meta.name || path.basename(vaultPath),
                root: meta.qmdRoot || vaultPath
            };
        }
        catch {
            return { collection: path.basename(vaultPath), root: vaultPath };
        }
    }
    return { collection: path.basename(vaultPath), root: vaultPath };
}
/**
 * Slugify a string for use as filename
 */
function slugify(text) {
    return text
        .toLowerCase()
        .replace(/[^\w\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-+|-+$/g, '')
        .trim();
}
/**
 * Scan a directory for markdown files
 */
function scanMarkdownFiles(dirPath) {
    const files = [];
    const resolvedPath = path.resolve(dirPath);
    if (!fs.existsSync(resolvedPath)) {
        return files;
    }
    const stat = fs.statSync(resolvedPath);
    if (stat.isFile() && resolvedPath.endsWith('.md')) {
        return [resolvedPath];
    }
    if (!stat.isDirectory()) {
        return files;
    }
    const entries = fs.readdirSync(resolvedPath, { withFileTypes: true });
    for (const entry of entries) {
        const fullPath = path.join(resolvedPath, entry.name);
        if (entry.isFile() && entry.name.endsWith('.md')) {
            files.push(fullPath);
        }
        else if (entry.isDirectory()) {
            files.push(...scanMarkdownFiles(fullPath));
        }
    }
    return files;
}
/**
 * Extract people mentioned in text using heuristics
 * Looks for patterns like:
 * - Names with email: "John Smith <john@example.com>"
 * - Names with roles: "John Smith (CTO)", "John Smith, CEO"
 * - Capitalized names after certain keywords: "met with John Smith", "contact John Smith"
 */
export function extractPeople(content) {
    const people = [];
    const seenNames = new Set();
    // Pattern: Name <email>
    const emailPattern = /([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\s*<([^>]+@[^>]+)>/g;
    let match;
    while ((match = emailPattern.exec(content)) !== null) {
        const name = match[1].trim();
        const email = match[2].trim();
        if (!seenNames.has(name.toLowerCase())) {
            seenNames.add(name.toLowerCase());
            people.push({ name, email });
        }
    }
    // Pattern: Name (Role) or Name, Role
    const rolePatterns = [
        /([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+)\s*\(([^)]+)\)/g,
        /([A-Z][a-z]+(?:\s+[A-Z][a-z]+)+),\s*(CEO|CTO|CFO|COO|VP|Director|Manager|Engineer|Designer|Lead|Head of [A-Za-z]+)/gi,
    ];
    for (const pattern of rolePatterns) {
        while ((match = pattern.exec(content)) !== null) {
            const name = match[1].trim();
            const role = match[2].trim();
            if (!seenNames.has(name.toLowerCase())) {
                seenNames.add(name.toLowerCase());
                people.push({ name, role });
            }
        }
    }
    // Pattern: Contact/met/spoke with/emailed Name
    // Note: Character classes [A-Z] are case-sensitive even with /i flag, so we use [A-Za-z]
    const contextPatterns = [
        /(?:contact|met with|spoke with|emailed|called|messaged|talked to|meeting with)\s+([A-Z][a-zA-Z]*(?:\s+[A-Z][a-zA-Z]*)+)/g,
        /([A-Z][a-zA-Z]*(?:\s+[A-Z][a-zA-Z]*)+)\s+(?:said|mentioned|suggested|recommended|asked|told me)/g,
    ];
    for (const pattern of contextPatterns) {
        while ((match = pattern.exec(content)) !== null) {
            const name = match[1].trim();
            if (!seenNames.has(name.toLowerCase()) && name.split(' ').length >= 2) {
                seenNames.add(name.toLowerCase());
                const lineStart = content.lastIndexOf('\n', match.index) + 1;
                const lineEnd = content.indexOf('\n', match.index + match[0].length);
                const context = content.slice(lineStart, lineEnd === -1 ? undefined : lineEnd).trim();
                people.push({ name, context: context.slice(0, 200) });
            }
        }
    }
    return people;
}
/**
 * Extract preferences from text using heuristics
 * Looks for patterns like:
 * - "prefers X", "prefer X", "I prefer X"
 * - "likes X", "like X", "I like X"
 * - "always use X", "never use X"
 * - "favorite X is Y"
 */
export function extractPreferences(content) {
    const preferences = [];
    const seenPrefs = new Set();
    const patterns = [
        // "prefers X" / "prefer X" / "I prefer X"
        /(?:I\s+)?prefer(?:s)?\s+(?:to\s+)?([^.,\n]+)/gi,
        // "likes X" / "like X"
        /(?:I\s+)?like(?:s)?\s+(?:to\s+)?([^.,\n]+)/gi,
        // "always use X"
        /always\s+(?:use|uses?)\s+([^.,\n]+)/gi,
        // "never use X"
        /never\s+(?:use|uses?)\s+([^.,\n]+)/gi,
        // "favorite X is Y"
        /(?:my\s+)?favorite\s+(\w+)\s+is\s+([^.,\n]+)/gi,
        // "prefer X over Y"
        /prefer(?:s)?\s+([^.,\n]+)\s+over\s+([^.,\n]+)/gi,
        // "use X instead of Y"
        /use(?:s)?\s+([^.,\n]+)\s+instead\s+of\s+([^.,\n]+)/gi,
    ];
    for (const pattern of patterns) {
        let match;
        while ((match = pattern.exec(content)) !== null) {
            const fullMatch = match[0].trim();
            const key = fullMatch.toLowerCase();
            if (!seenPrefs.has(key) && fullMatch.length > 5 && fullMatch.length < 200) {
                seenPrefs.add(key);
                const lineStart = content.lastIndexOf('\n', match.index) + 1;
                const lineEnd = content.indexOf('\n', match.index + match[0].length);
                const context = content.slice(lineStart, lineEnd === -1 ? undefined : lineEnd).trim();
                // Extract subject and preference from the match
                let subject = 'general';
                let preference = fullMatch;
                if (match[2]) {
                    // Pattern like "favorite X is Y" or "prefer X over Y"
                    subject = match[1].trim();
                    preference = match[2].trim();
                }
                else if (match[1]) {
                    preference = match[1].trim();
                }
                preferences.push({ subject, preference, context: context.slice(0, 200) });
            }
        }
    }
    return preferences;
}
/**
 * Extract decisions from text using heuristics
 * Looks for patterns like:
 * - "decided to X"
 * - "decision: X"
 * - "we chose X"
 * - "going with X"
 */
export function extractDecisions(content) {
    const decisions = [];
    const seenDecisions = new Set();
    const patterns = [
        // "decided to X"
        /(?:I\s+|we\s+)?decided\s+(?:to\s+)?([^.,\n]+)/gi,
        // "decision: X" or "Decision - X"
        /decision[:\s-]+([^.,\n]+)/gi,
        // "we chose X" / "chose to X"
        /(?:we\s+)?chose\s+(?:to\s+)?([^.,\n]+)/gi,
        // "going with X"
        /going\s+with\s+([^.,\n]+)/gi,
        // "settled on X"
        /settled\s+on\s+([^.,\n]+)/gi,
        // "will use X" / "using X going forward"
        /(?:will\s+use|using)\s+([^.,\n]+)\s+(?:going\s+forward|from\s+now\s+on)/gi,
    ];
    for (const pattern of patterns) {
        let match;
        while ((match = pattern.exec(content)) !== null) {
            const decision = match[1].trim();
            const key = decision.toLowerCase();
            if (!seenDecisions.has(key) && decision.length > 5 && decision.length < 200) {
                seenDecisions.add(key);
                const lineStart = content.lastIndexOf('\n', match.index) + 1;
                const lineEnd = content.indexOf('\n', match.index + match[0].length);
                const context = content.slice(lineStart, lineEnd === -1 ? undefined : lineEnd).trim();
                // Generate a title from the decision
                const title = decision.length > 50
                    ? decision.slice(0, 50).trim() + '...'
                    : decision;
                decisions.push({ title, decision, context: context.slice(0, 200) });
            }
        }
    }
    return decisions;
}
/**
 * Extract tasks/todos from text using heuristics
 * Looks for patterns like:
 * - "- [ ] task" (markdown checkbox)
 * - "TODO: task"
 * - "need to X"
 * - "should X"
 */
export function extractTasks(content) {
    const tasks = [];
    const seenTasks = new Set();
    const patterns = [
        // Markdown checkbox "- [ ] task"
        /^[\s]*[-*]\s*\[\s*\]\s*(.+)$/gm,
        // "TODO: task" or "TODO - task"
        /TODO[:\s-]+(.+)/gi,
        // "FIXME: task"
        /FIXME[:\s-]+(.+)/gi,
        // "need to X"
        /(?:I\s+|we\s+)?need\s+to\s+([^.,\n]+)/gi,
        // "should X" (but not "should have" which is past)
        /(?:I\s+|we\s+)?should\s+(?!have)([^.,\n]+)/gi,
        // "must X"
        /(?:I\s+|we\s+)?must\s+([^.,\n]+)/gi,
        // "remember to X"
        /remember\s+to\s+([^.,\n]+)/gi,
        // "don't forget to X"
        /don'?t\s+forget\s+to\s+([^.,\n]+)/gi,
    ];
    for (const pattern of patterns) {
        let match;
        while ((match = pattern.exec(content)) !== null) {
            const taskText = match[1].trim();
            const key = taskText.toLowerCase();
            if (!seenTasks.has(key) && taskText.length > 3 && taskText.length < 200) {
                seenTasks.add(key);
                // Determine priority based on keywords
                let priority = 'medium';
                const lowerTask = taskText.toLowerCase();
                if (lowerTask.includes('urgent') || lowerTask.includes('asap') || lowerTask.includes('critical')) {
                    priority = 'critical';
                }
                else if (lowerTask.includes('important') || lowerTask.includes('high priority')) {
                    priority = 'high';
                }
                else if (lowerTask.includes('low priority') || lowerTask.includes('eventually') || lowerTask.includes('someday')) {
                    priority = 'low';
                }
                tasks.push({ title: taskText, priority });
            }
        }
    }
    return tasks;
}
/**
 * Extract all structured data from markdown content
 */
export function extractFromContent(content) {
    return {
        people: extractPeople(content),
        preferences: extractPreferences(content),
        decisions: extractDecisions(content),
        tasks: extractTasks(content),
    };
}
/**
 * Scan a source directory and extract all structured data
 */
export function scanAndExtract(sourcePath) {
    const files = scanMarkdownFiles(sourcePath);
    const combined = {
        people: [],
        preferences: [],
        decisions: [],
        tasks: [],
    };
    for (const file of files) {
        try {
            const content = fs.readFileSync(file, 'utf-8');
            const extracted = extractFromContent(content);
            combined.people.push(...extracted.people);
            combined.preferences.push(...extracted.preferences);
            combined.decisions.push(...extracted.decisions);
            combined.tasks.push(...extracted.tasks);
        }
        catch {
            // Skip files that can't be read
        }
    }
    // Deduplicate by name/title
    const seenPeople = new Set();
    combined.people = combined.people.filter(p => {
        const key = p.name.toLowerCase();
        if (seenPeople.has(key))
            return false;
        seenPeople.add(key);
        return true;
    });
    const seenPrefs = new Set();
    combined.preferences = combined.preferences.filter(p => {
        const key = `${p.subject}:${p.preference}`.toLowerCase();
        if (seenPrefs.has(key))
            return false;
        seenPrefs.add(key);
        return true;
    });
    const seenDecisions = new Set();
    combined.decisions = combined.decisions.filter(d => {
        const key = d.decision.toLowerCase();
        if (seenDecisions.has(key))
            return false;
        seenDecisions.add(key);
        return true;
    });
    const seenTasks = new Set();
    combined.tasks = combined.tasks.filter(t => {
        const key = t.title.toLowerCase();
        if (seenTasks.has(key))
            return false;
        seenTasks.add(key);
        return true;
    });
    return combined;
}
/**
 * Check if a similar file already exists in the vault
 */
function fileExistsWithSimilarName(dir, slug) {
    if (!fs.existsSync(dir))
        return false;
    const files = fs.readdirSync(dir);
    const targetSlug = slug.toLowerCase();
    return files.some(f => {
        const fileSlug = path.basename(f, '.md').toLowerCase();
        return fileSlug === targetSlug || fileSlug.includes(targetSlug) || targetSlug.includes(fileSlug);
    });
}
/**
 * Write a person primitive to the vault
 */
function writePerson(vaultPath, person, force) {
    const peopleDir = path.join(vaultPath, 'people');
    fs.mkdirSync(peopleDir, { recursive: true });
    const slug = slugify(person.name);
    if (!slug)
        return null;
    const filePath = path.join(peopleDir, `${slug}.md`);
    if (!force && (fs.existsSync(filePath) || fileExistsWithSimilarName(peopleDir, slug))) {
        return null;
    }
    const template = loadTemplateDefinition('person');
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    let content;
    if (template) {
        const rendered = renderDocumentFromTemplate(template, {
            title: person.name,
            now,
            overrides: {
                relationship: person.role ? 'colleague' : 'contact',
            },
        });
        // Replace placeholder content with actual data
        let body = rendered.content;
        if (person.context) {
            body = body.replace(/## Context\n-\s*/, `## Context\n- ${person.context}\n`);
        }
        if (person.email || person.role) {
            const details = [];
            if (person.email)
                details.push(`- Contact: ${person.email}`);
            if (person.role)
                details.push(`- Role: ${person.role}`);
            body = body.replace(/## Details\n- Contact:\n- Role:\n- Timezone:/, `## Details\n${details.join('\n')}\n- Timezone:`);
        }
        content = matter.stringify(body, rendered.frontmatter);
    }
    else {
        // Fallback if template not found
        const frontmatter = {
            title: person.name,
            date,
            type: 'person',
            relationship: person.role ? 'colleague' : 'contact',
        };
        let body = `# ${person.name}\n\n## Context\n`;
        if (person.context)
            body += `- ${person.context}\n`;
        else
            body += '- \n';
        body += '\n## Details\n';
        if (person.email)
            body += `- Contact: ${person.email}\n`;
        else
            body += '- Contact:\n';
        if (person.role)
            body += `- Role: ${person.role}\n`;
        else
            body += '- Role:\n';
        body += '- Timezone:\n';
        body += `\n## History\n- ${date}: Added from memory import\n`;
        content = matter.stringify(body, frontmatter);
    }
    fs.writeFileSync(filePath, content);
    return slug;
}
/**
 * Write a preference to the vault as a memory in preferences/
 */
function writePreference(vaultPath, pref, force) {
    const prefsDir = path.join(vaultPath, 'preferences');
    fs.mkdirSync(prefsDir, { recursive: true });
    const slug = slugify(`${pref.subject}-${pref.preference}`.slice(0, 60));
    if (!slug)
        return null;
    const filePath = path.join(prefsDir, `${slug}.md`);
    if (!force && (fs.existsSync(filePath) || fileExistsWithSimilarName(prefsDir, slug))) {
        return null;
    }
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const frontmatter = {
        title: `${pref.subject}: ${pref.preference}`.slice(0, 100),
        date,
        type: 'preference',
        category: pref.subject,
    };
    let body = `# ${frontmatter.title}\n\n`;
    body += `## Preference\n- ${pref.preference}\n`;
    if (pref.context) {
        body += `\n## Context\n- ${pref.context}\n`;
    }
    body += `\n## Source\n- Imported from memory on ${date}\n`;
    const content = matter.stringify(body, frontmatter);
    fs.writeFileSync(filePath, content);
    return slug;
}
/**
 * Write a decision to the vault
 */
function writeDecision(vaultPath, decision, force) {
    const decisionsDir = path.join(vaultPath, 'decisions');
    fs.mkdirSync(decisionsDir, { recursive: true });
    const slug = slugify(decision.title);
    if (!slug)
        return null;
    const filePath = path.join(decisionsDir, `${slug}.md`);
    if (!force && (fs.existsSync(filePath) || fileExistsWithSimilarName(decisionsDir, slug))) {
        return null;
    }
    const template = loadTemplateDefinition('decision');
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    let content;
    if (template) {
        const rendered = renderDocumentFromTemplate(template, {
            title: decision.title,
            now,
            overrides: {
                status: 'decided',
            },
        });
        let body = rendered.content;
        if (decision.context) {
            body = body.replace(/## Context\n-\s*/, `## Context\n- ${decision.context}\n`);
        }
        body = body.replace(/## Decision\n-\s*/, `## Decision\n- ${decision.decision}\n`);
        body = body.replace(/## Consequences\n-\s*/, `## Consequences\n- Imported from memory on ${date}\n`);
        content = matter.stringify(body, rendered.frontmatter);
    }
    else {
        const frontmatter = {
            title: decision.title,
            date,
            type: 'decision',
            status: 'decided',
        };
        let body = `# Decision: ${decision.title}\n\n`;
        body += `## Context\n`;
        if (decision.context)
            body += `- ${decision.context}\n`;
        else
            body += '- \n';
        body += `\n## Decision\n- ${decision.decision}\n`;
        body += `\n## Consequences\n- Imported from memory on ${date}\n`;
        content = matter.stringify(body, frontmatter);
    }
    fs.writeFileSync(filePath, content);
    return slug;
}
/**
 * Write a task to the vault
 */
function writeTask(vaultPath, task, force) {
    const tasksDir = path.join(vaultPath, 'tasks');
    fs.mkdirSync(tasksDir, { recursive: true });
    const slug = slugify(task.title);
    if (!slug)
        return null;
    const filePath = path.join(tasksDir, `${slug}.md`);
    if (!force && (fs.existsSync(filePath) || fileExistsWithSimilarName(tasksDir, slug))) {
        return null;
    }
    const template = loadTemplateDefinition('task');
    const now = new Date();
    const datetime = now.toISOString();
    let content;
    if (template) {
        const rendered = renderDocumentFromTemplate(template, {
            title: task.title,
            now,
            overrides: {
                status: 'open',
                priority: task.priority || 'medium',
                source: 'memory-import',
                description: task.description,
            },
            frontmatter: { pruneEmpty: true },
        });
        content = rendered.markdown;
    }
    else {
        const frontmatter = {
            status: 'open',
            source: 'memory-import',
            created: datetime,
            updated: datetime,
            priority: task.priority || 'medium',
        };
        if (task.description)
            frontmatter.description = task.description;
        const body = `# ${task.title}\n\n`;
        content = matter.stringify(body, frontmatter);
    }
    fs.writeFileSync(filePath, content);
    return slug;
}
/**
 * Import extracted data into the vault
 */
export function importToVault(vaultPath, extracted, force) {
    const summary = {
        created: { people: [], preferences: [], decisions: [], tasks: [] },
        skipped: { people: [], preferences: [], decisions: [], tasks: [] },
    };
    for (const person of extracted.people) {
        const slug = writePerson(vaultPath, person, force);
        if (slug) {
            summary.created.people.push(person.name);
        }
        else {
            summary.skipped.people.push(person.name);
        }
    }
    for (const pref of extracted.preferences) {
        const slug = writePreference(vaultPath, pref, force);
        if (slug) {
            summary.created.preferences.push(`${pref.subject}: ${pref.preference}`.slice(0, 50));
        }
        else {
            summary.skipped.preferences.push(`${pref.subject}: ${pref.preference}`.slice(0, 50));
        }
    }
    for (const decision of extracted.decisions) {
        const slug = writeDecision(vaultPath, decision, force);
        if (slug) {
            summary.created.decisions.push(decision.title);
        }
        else {
            summary.skipped.decisions.push(decision.title);
        }
    }
    for (const task of extracted.tasks) {
        const slug = writeTask(vaultPath, task, force);
        if (slug) {
            summary.created.tasks.push(task.title);
        }
        else {
            summary.skipped.tasks.push(task.title);
        }
    }
    return summary;
}
/**
 * Print import summary to console
 */
function printImportSummary(summary) {
    const totalCreated = summary.created.people.length +
        summary.created.preferences.length +
        summary.created.decisions.length +
        summary.created.tasks.length;
    const totalSkipped = summary.skipped.people.length +
        summary.skipped.preferences.length +
        summary.skipped.decisions.length +
        summary.skipped.tasks.length;
    console.log('\n📥 Memory Import Summary');
    console.log('─'.repeat(40));
    if (summary.created.people.length > 0) {
        console.log(`✓ People (${summary.created.people.length}):`);
        for (const name of summary.created.people.slice(0, 5)) {
            console.log(`    - ${name}`);
        }
        if (summary.created.people.length > 5) {
            console.log(`    ... and ${summary.created.people.length - 5} more`);
        }
    }
    if (summary.created.preferences.length > 0) {
        console.log(`✓ Preferences (${summary.created.preferences.length}):`);
        for (const pref of summary.created.preferences.slice(0, 5)) {
            console.log(`    - ${pref}`);
        }
        if (summary.created.preferences.length > 5) {
            console.log(`    ... and ${summary.created.preferences.length - 5} more`);
        }
    }
    if (summary.created.decisions.length > 0) {
        console.log(`✓ Decisions (${summary.created.decisions.length}):`);
        for (const dec of summary.created.decisions.slice(0, 5)) {
            console.log(`    - ${dec}`);
        }
        if (summary.created.decisions.length > 5) {
            console.log(`    ... and ${summary.created.decisions.length - 5} more`);
        }
    }
    if (summary.created.tasks.length > 0) {
        console.log(`✓ Tasks (${summary.created.tasks.length}):`);
        for (const task of summary.created.tasks.slice(0, 5)) {
            console.log(`    - ${task}`);
        }
        if (summary.created.tasks.length > 5) {
            console.log(`    ... and ${summary.created.tasks.length - 5} more`);
        }
    }
    if (totalSkipped > 0) {
        console.log(`\n⊘ Skipped ${totalSkipped} items (already exist or similar)`);
    }
    console.log('─'.repeat(40));
    console.log(`Total: ${totalCreated} created, ${totalSkipped} skipped`);
}
export async function setupCommand(options = {}) {
    const target = resolveVaultTarget(options.vault);
    if (target.existed && !fs.statSync(target.vaultPath).isDirectory()) {
        throw new Error(`Vault path is not a directory: ${target.vaultPath}`);
    }
    if (!target.existed)
        fs.mkdirSync(target.vaultPath, { recursive: true });
    console.log(`${target.existed ? 'Found' : 'Created'} vault path (${target.source}): ${target.vaultPath}`);
    const initialized = ensureVaultStructure(target.vaultPath);
    console.log(initialized ? '✓ Initialized vault structure.' : '✓ Vault structure already present.');
    const force = options.force ?? false;
    const theme = options.theme ?? 'neural';
    // Determine what to set up
    const explicitFlags = options.graphColors !== undefined || options.bases !== undefined;
    const doGraphColors = explicitFlags ? (options.graphColors !== false) : true;
    const doBases = explicitFlags ? (options.bases !== false) : true;
    // Graph colors
    if (doGraphColors && theme !== 'none') {
        const wrote = writeGraphColors(target.vaultPath, theme, force);
        if (wrote) {
            console.log(`✓ Graph colors configured (${theme} theme)`);
        }
        else {
            const obsidianDir = path.join(target.vaultPath, '.obsidian');
            if (!fs.existsSync(obsidianDir)) {
                console.log('⊘ No .obsidian directory — skipping graph colors (not an Obsidian vault)');
            }
            else {
                console.log('⊘ Graph colors already exist (use --force to overwrite)');
            }
        }
    }
    else if (doGraphColors && theme === 'none') {
        console.log('⊘ Graph colors skipped (--theme none)');
    }
    // Bases
    if (doBases) {
        const count = writeBases(target.vaultPath, force);
        if (count > 0) {
            console.log(`✓ Created ${count} Obsidian Bases view${count > 1 ? 's' : ''}`);
        }
        else {
            console.log('⊘ Bases views already exist (use --force to overwrite)');
        }
    }
    // qmd
    if (hasQmd()) {
        const { collection, root } = getQmdConfig(target.vaultPath);
        try {
            execFileSync('qmd', withQmdIndexArgs(['collection', 'add', root, '--name', collection, '--mask', '**/*.md'], options.qmdIndexName), {
                stdio: 'ignore'
            });
            console.log(`✓ qmd collection ready: ${collection}`);
        }
        catch {
            console.log('⊘ qmd collection already exists.');
        }
    }
    else {
        console.log('⊘ qmd not found — skipping semantic search setup.');
    }
    console.log('\nTip: add this to your shell config:');
    console.log(`  export CLAWVAULT_PATH="${target.vaultPath}"`);
    console.log('\nCustomize further:');
    console.log('  clawvault setup --theme neural     # Neural neural graph colors');
    console.log('  clawvault setup --theme minimal        # Subtle category colors');
    console.log('  clawvault setup --no-bases --no-graph-colors  # Structure only');
    console.log('  clawvault setup --force                 # Overwrite existing configs');
}
//# sourceMappingURL=setup.js.map